settings:
  allowed_values:
    -
      label: Rouge
    -
      label: Orange
    -
      label: Jaune
    -
      label: Vert
    -
      label: Turquoise
    -
      label: Bleu
    -
      label: Violet
    -
      label: Rose
